//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiNeptuno2020.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Neptuno2020Entities : DbContext
    {
        public Neptuno2020Entities()
            : base("name=Neptuno2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Listar_Productos_API_Result> Listar_Productos_API()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Listar_Productos_API_Result>("Listar_Productos_API");
        }
    
        public virtual ObjectResult<PedidosProductoFechas_API_Result> PedidosProductoFechas_API(Nullable<int> idproducto, Nullable<System.DateTime> fecha1, Nullable<System.DateTime> fecha2)
        {
            var idproductoParameter = idproducto.HasValue ?
                new ObjectParameter("idproducto", idproducto) :
                new ObjectParameter("idproducto", typeof(int));
    
            var fecha1Parameter = fecha1.HasValue ?
                new ObjectParameter("fecha1", fecha1) :
                new ObjectParameter("fecha1", typeof(System.DateTime));
    
            var fecha2Parameter = fecha2.HasValue ?
                new ObjectParameter("fecha2", fecha2) :
                new ObjectParameter("fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PedidosProductoFechas_API_Result>("PedidosProductoFechas_API", idproductoParameter, fecha1Parameter, fecha2Parameter);
        }

        public System.Data.Entity.DbSet<WebApiNeptuno2020.Models.PedidosProductoFechas_API_Result> PedidosProductoFechas_API_Result { get; set; }
    }
}
