//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEC3ManuelCabos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta_Detalle
    {
        public int num_vta { get; set; }
        public string cod_pel { get; set; }
        public Nullable<int> cant { get; set; }
        public Nullable<int> cod_for { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string eliminado { get; set; }
    
        public virtual Formatos Formatos { get; set; }
        public virtual Peliculas Peliculas { get; set; }
        public virtual Venta_Cabecera Venta_Cabecera { get; set; }
    }
}
