//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEC3ManuelCabos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDVIDEOS2019Entities : DbContext
    {
        public BDVIDEOS2019Entities()
            : base("name=BDVIDEOS2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actores> Actores { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Formatos> Formatos { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Peliculas> Peliculas { get; set; }
        public virtual DbSet<Venta_Cabecera> Venta_Cabecera { get; set; }
        public virtual DbSet<Venta_Detalle> Venta_Detalle { get; set; }
    
        public virtual ObjectResult<listar_peliculas_Result> listar_peliculas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listar_peliculas_Result>("listar_peliculas");
        }
    
        public virtual ObjectResult<sp_listar_peliculas_Result> sp_listar_peliculas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_peliculas_Result>("sp_listar_peliculas");
        }
    
        public virtual ObjectResult<sp_buscar_peliculas_Result> sp_buscar_peliculas(string cod_gen, Nullable<int> año)
        {
            var cod_genParameter = cod_gen != null ?
                new ObjectParameter("cod_gen", cod_gen) :
                new ObjectParameter("cod_gen", typeof(string));
    
            var añoParameter = año.HasValue ?
                new ObjectParameter("año", año) :
                new ObjectParameter("año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_buscar_peliculas_Result>("sp_buscar_peliculas", cod_genParameter, añoParameter);
        }
    }
}
