//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CarritoCompra.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Articulos
    {
        [Key]
        public string art_cod { get; set; }
        public string art_nom { get; set; }
        public string art_uni { get; set; }
        public decimal art_pre { get; set; }
        public int art_stk { get; set; }
    }
}
