//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CarritoCompra.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDVENTAS2020Entities : DbContext
    {
        public BDVENTAS2020Entities()
            : base("name=BDVENTAS2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulos> Articulos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
    
        public virtual int PA_GRABAR_FAC_DETA(string fAC_NUM, string aRT_COD, Nullable<int> aRT_CAN, Nullable<decimal> aRT_PRE)
        {
            var fAC_NUMParameter = fAC_NUM != null ?
                new ObjectParameter("FAC_NUM", fAC_NUM) :
                new ObjectParameter("FAC_NUM", typeof(string));
    
            var aRT_CODParameter = aRT_COD != null ?
                new ObjectParameter("ART_COD", aRT_COD) :
                new ObjectParameter("ART_COD", typeof(string));
    
            var aRT_CANParameter = aRT_CAN.HasValue ?
                new ObjectParameter("ART_CAN", aRT_CAN) :
                new ObjectParameter("ART_CAN", typeof(int));
    
            var aRT_PREParameter = aRT_PRE.HasValue ?
                new ObjectParameter("ART_PRE", aRT_PRE) :
                new ObjectParameter("ART_PRE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_GRABAR_FAC_DETA", fAC_NUMParameter, aRT_CODParameter, aRT_CANParameter, aRT_PREParameter);
        }
    
        public virtual ObjectResult<string> PA_GRABAR_WEB_FAC_CABE(string cLI_COD, Nullable<decimal> fAC_TOTAL)
        {
            var cLI_CODParameter = cLI_COD != null ?
                new ObjectParameter("CLI_COD", cLI_COD) :
                new ObjectParameter("CLI_COD", typeof(string));
    
            var fAC_TOTALParameter = fAC_TOTAL.HasValue ?
                new ObjectParameter("FAC_TOTAL", fAC_TOTAL) :
                new ObjectParameter("FAC_TOTAL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PA_GRABAR_WEB_FAC_CABE", cLI_CODParameter, fAC_TOTALParameter);
        }

        public System.Data.Entity.DbSet<MVC_CarritoCompra.Models.Carrito> Carritoes { get; set; }
    }
}
