//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuentas", Namespace="http://schemas.datacontract.org/2004/07/WcfBDBancos2020")]
    [System.SerializableAttribute()]
    public partial class Cuentas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cli_codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_ctaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string num_ctaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal saldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cli_codigo {
            get {
                return this.cli_codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.cli_codigoField, value) != true)) {
                    this.cli_codigoField = value;
                    this.RaisePropertyChanged("cli_codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_cta {
            get {
                return this.cod_ctaField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_ctaField, value) != true)) {
                    this.cod_ctaField = value;
                    this.RaisePropertyChanged("cod_cta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string num_cta {
            get {
                return this.num_ctaField;
            }
            set {
                if ((object.ReferenceEquals(this.num_ctaField, value) != true)) {
                    this.num_ctaField = value;
                    this.RaisePropertyChanged("num_cta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicioBancos")]
    public interface IServicioBancos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBancos/Grabar_Cuenta", ReplyAction="http://tempuri.org/IServicioBancos/Grabar_CuentaResponse")]
        string Grabar_Cuenta(WindowsFormsApplication1.ServiceReference1.Cuentas obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBancos/Grabar_Cuenta", ReplyAction="http://tempuri.org/IServicioBancos/Grabar_CuentaResponse")]
        System.Threading.Tasks.Task<string> Grabar_CuentaAsync(WindowsFormsApplication1.ServiceReference1.Cuentas obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBancos/Listar_Cuentas", ReplyAction="http://tempuri.org/IServicioBancos/Listar_CuentasResponse")]
        WindowsFormsApplication1.ServiceReference1.Cuentas[] Listar_Cuentas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBancos/Listar_Cuentas", ReplyAction="http://tempuri.org/IServicioBancos/Listar_CuentasResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Cuentas[]> Listar_CuentasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioBancosChannel : WindowsFormsApplication1.ServiceReference1.IServicioBancos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioBancosClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.IServicioBancos>, WindowsFormsApplication1.ServiceReference1.IServicioBancos {
        
        public ServicioBancosClient() {
        }
        
        public ServicioBancosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioBancosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBancosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBancosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Grabar_Cuenta(WindowsFormsApplication1.ServiceReference1.Cuentas obj) {
            return base.Channel.Grabar_Cuenta(obj);
        }
        
        public System.Threading.Tasks.Task<string> Grabar_CuentaAsync(WindowsFormsApplication1.ServiceReference1.Cuentas obj) {
            return base.Channel.Grabar_CuentaAsync(obj);
        }
        
        public WindowsFormsApplication1.ServiceReference1.Cuentas[] Listar_Cuentas() {
            return base.Channel.Listar_Cuentas();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.Cuentas[]> Listar_CuentasAsync() {
            return base.Channel.Listar_CuentasAsync();
        }
    }
}
