//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiBDVIDEOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDVIDEOS2016Entities : DbContext
    {
        public BDVIDEOS2016Entities()
            : base("name=BDVIDEOS2016Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<int> Listar_Anios_Alquiler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<int>("Listar_Anios_Alquiler");
        }
    
        public virtual ObjectResult<Top_Peliculas_Alquiler_Anio_Result> Top_Peliculas_Alquiler_Anio(int n, int anio)
        {
            var nParameter = new ObjectParameter("n", n);
            var anioParameter = new ObjectParameter("anio", anio);
                
            //var nParameter = n.HasValue ?
            //    new ObjectParameter("n", n) :
            //    new ObjectParameter("n", typeof(int));

            //var anioParameter = anio.HasValue ?
            //    new ObjectParameter("anio", anio) :
            //    new ObjectParameter("anio", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Top_Peliculas_Alquiler_Anio_Result>("Top_Peliculas_Alquiler_Anio", nParameter, anioParameter);
        }

        public System.Data.Entity.DbSet<WebApiBDVIDEOS.Models.Top_Peliculas_Alquiler_Anio_Result> Top_Peliculas_Alquiler_Anio_Result { get; set; }
    }
}
