//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC2_ManuelCabos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int nrocita { get; set; }
        public string codmed { get; set; }
        public string codpac { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<decimal> pago { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> estado { get; set; }
        public string descrip { get; set; }
    
        public virtual Medicos Medicos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
