//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_BDTRANSITO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDTRANSITO2016Entities : DbContext
    {
        public BDTRANSITO2016Entities()
            : base("name=BDTRANSITO2016Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<LISTAR_PROPIETARIOS_Result> LISTAR_PROPIETARIOS(string nOMBRE)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LISTAR_PROPIETARIOS_Result>("LISTAR_PROPIETARIOS", nOMBREParameter);
        }
    
        public virtual int PAGAR_PAPELETA(Nullable<int> nROPAP)
        {
            var nROPAPParameter = nROPAP.HasValue ?
                new ObjectParameter("NROPAP", nROPAP) :
                new ObjectParameter("NROPAP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAGAR_PAPELETA", nROPAPParameter);
        }
    
        public virtual ObjectResult<PAPELETAS_PROPIETARIO_Result> PAPELETAS_PROPIETARIO(string dNIPRO)
        {
            var dNIPROParameter = dNIPRO != null ?
                new ObjectParameter("DNIPRO", dNIPRO) :
                new ObjectParameter("DNIPRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PAPELETAS_PROPIETARIO_Result>("PAPELETAS_PROPIETARIO", dNIPROParameter);
        }
    }
}
