//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BDBANCOS_EF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDBANCOS2018Entities : DbContext
    {
        public BDBANCOS2018Entities()
            : base("name=BDBANCOS2018Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        public virtual DbSet<Tipo_Cuentas> Tipo_Cuentas { get; set; }
    
        public virtual int usp_Actualizar_Cuenta(string num_cta, string cli_codigo, string cod_cta, Nullable<decimal> saldo)
        {
            var num_ctaParameter = num_cta != null ?
                new ObjectParameter("num_cta", num_cta) :
                new ObjectParameter("num_cta", typeof(string));
    
            var cli_codigoParameter = cli_codigo != null ?
                new ObjectParameter("cli_codigo", cli_codigo) :
                new ObjectParameter("cli_codigo", typeof(string));
    
            var cod_ctaParameter = cod_cta != null ?
                new ObjectParameter("cod_cta", cod_cta) :
                new ObjectParameter("cod_cta", typeof(string));
    
            var saldoParameter = saldo.HasValue ?
                new ObjectParameter("saldo", saldo) :
                new ObjectParameter("saldo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Actualizar_Cuenta", num_ctaParameter, cli_codigoParameter, cod_ctaParameter, saldoParameter);
        }
    
        public virtual ObjectResult<usp_Listar_Cuentas_Result> usp_Listar_Cuentas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Listar_Cuentas_Result>("usp_Listar_Cuentas");
        }
    
        public virtual ObjectResult<usp_Listar_Cuentasv2_Result1> usp_Listar_Cuentasv2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Listar_Cuentasv2_Result1>("usp_Listar_Cuentasv2");
        }

        public System.Data.Entity.DbSet<MVC_BDBANCOS_EF.Models.usp_Listar_Cuentas_Result> usp_Listar_Cuentas_Result { get; set; }
    }
}
