//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BDBANCOS_EF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Clientes
    {
        [Key]
        public string cli_codigo { get; set; }
        public string cli_nombre { get; set; }
        public string cli_telefono { get; set; }
        public string cli_ruc { get; set; }
        public string cli_direccion { get; set; }
    }
}
