//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BDBANCOS_EF.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class usp_Listar_Cuentasv2_Result1
    {
        [Key]
        public string num_cta { get; set; }
        public string cod_cta { get; set; }
        public string desc_cta { get; set; }
        public string cli_codigo { get; set; }
        public string cli_nombre { get; set; }
        public string cli_ruc { get; set; }
    }
}
