//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiNeptuno.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Neptuno2019Entities : DbContext
    {
        public Neptuno2019Entities()
            : base("name=Neptuno2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
    
        public virtual ObjectResult<sp_api_listar_clientes_Result> sp_api_listar_clientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_api_listar_clientes_Result>("sp_api_listar_clientes");
        }
    }
}
