USE BDTRANSITO2016
GO

CREATE PROCEDURE LISTAR_PROPIETARIOS
@NOMBRE VARCHAR(20)='%'
AS
	SELECT P.DNIPRO, P.NOMPRO
	FROM PROPIETARIOS P
		WHERE P.NOMPRO LIKE @NOMBRE+'%'
GO
		
EXECUTE LISTAR_PROPIETARIOS ''
GO

CREATE PROCEDURE PAPELETAS_PROPIETARIO
@DNIPRO CHAR(8)
AS
	SELECT P.NROPAP, P.NROPLA, I.DESINF, 
			CONVERT(VARCHAR(10),P.PAPFECHA, 103) AS PAPFECHA,
			I.IMPORTE, P.PAGADO
	FROM PAPELETAS P INNER JOIN INFRACCIONES I
		ON P.CODINF=I.CODINF
			INNER JOIN VEHICULOS V
				ON P.NROPLA=V.NROPLA
	WHERE V.DNIPRO=@DNIPRO
		--AND P.PAGADO='No'
GO
		
EXECUTE PAPELETAS_PROPIETARIO '11223344'
GO

CREATE PROCEDURE PAGAR_PAPELETA
@NROPAP INT
AS
	UPDATE PAPELETAS
		SET PAGADO='Si',
			FECPAGO=GETDATE()
	WHERE NROPAP=@NROPAP
GO
	
--EXECUTE PAGAR_PAPELETA 100023
--GO
			